<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProyectoSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('tbl_proyectos')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        DB::table('tbl_proyectos')->insert([
            [
                'codigo' => 'PRY-001',
                'nombre' => 'TRATO DIRECTO Nº 45/2011',
                'id_comuna' => 1,
                'supervisor_1' => null,
                'supervisor_2' => null,
                'nmro_beneficiarios' => 9,
                'nmro_resolucion' => null,
                'fecha_resolucion' => null,
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => null,
                'id_programa' => 6,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-002',
                'nombre' => 'RURALES AMPLIACION CUNCUMEN',
                'id_comuna' => 1,
                'supervisor_1' => 'Francisco Cadenas',
                'supervisor_2' => null,
                'nmro_beneficiarios' => 7,
                'nmro_resolucion' => 4508,
                'fecha_resolucion' => '2019-06-28',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2026-10-14',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-003',
                'nombre' => '3 BENEFICIARIOS DS 49 (CESAR, LUIS, SUSANA)',
                'id_comuna' => 1,
                'supervisor_1' => 'Francisco Cadenas',
                'supervisor_2' => null,
                'nmro_beneficiarios' => 3,
                'nmro_resolucion' => null,
                'fecha_resolucion' => null,
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2025-04-07',
                'id_programa' => 3,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-004',
                'nombre' => 'CONVENIO MARCO',
                'id_comuna' => 12,
                'supervisor_1' => null,
                'supervisor_2' => null,
                'nmro_beneficiarios' => 0,
                'nmro_resolucion' => null,
                'fecha_resolucion' => null,
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => null,
                'id_programa' => 7,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-005',
                'nombre' => 'BENEFICIARIOS DS 49 (SAN ANTONIO)',
                'id_comuna' => 1,
                'supervisor_1' => 'Francisco Cadenas',
                'supervisor_2' => null,
                'nmro_beneficiarios' => 15,
                'nmro_resolucion' => null,
                'fecha_resolucion' => null,
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => null,
                'id_programa' => 4,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-006',
                'nombre' => 'RURALES AMPLIACION QUILLOTA',
                'id_comuna' => 2,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 9,
                'nmro_resolucion' => 3317,
                'fecha_resolucion' => '2020-06-04',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2022-03-04',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-007',
                'nombre' => 'RURALES AMPLIACION LA CALERA',
                'id_comuna' => 3,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 10,
                'nmro_resolucion' => 2833,
                'fecha_resolucion' => '2020-05-07',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2022-02-07',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-008',
                'nombre' => 'MARTA DELIA VERA ROMERO',
                'id_comuna' => 2,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 2852,
                'fecha_resolucion' => '2023-04-14',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-04-01',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-009',
                'nombre' => 'BLAS ELADIO PEÑA GONZÁLEZ',
                'id_comuna' => 3,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 3060,
                'fecha_resolucion' => '2023-04-20',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-04-01',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-010',
                'nombre' => 'NELSON AGUSTÍN FERNÁNDEZ VERGARA',
                'id_comuna' => 3,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 3607,
                'fecha_resolucion' => '2023-05-02',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-04-01',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-011',
                'nombre' => 'MARIZA DEL CARMEN ZÚÑIGA MENA',
                'id_comuna' => 3,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 3608,
                'fecha_resolucion' => '2023-05-02',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-04-01',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-012',
                'nombre' => 'BARBARA MUÑIZ JIMÉNEZ',
                'id_comuna' => 4,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 3530,
                'fecha_resolucion' => '2023-04-28',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2025-01-28',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-013',
                'nombre' => 'YIRLAY KARINA TORREJÓN TAPIA',
                'id_comuna' => 4,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 3497,
                'fecha_resolucion' => '2023-04-28',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2025-01-28',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-014',
                'nombre' => 'ERNESTINA OYANEDEL GOMEZ',
                'id_comuna' => 4,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 3602,
                'fecha_resolucion' => '2023-05-02',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2025-02-02',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-015',
                'nombre' => 'ROSA VELASQUEZ',
                'id_comuna' => 2,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => null,
                'fecha_resolucion' => null,
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => null,
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-016',
                'nombre' => 'MARCELO REBOLLEDO',
                'id_comuna' => 2,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => null,
                'fecha_resolucion' => null,
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => null,
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-017',
                'nombre' => 'MARISELA CHACANA',
                'id_comuna' => 2,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => null,
                'fecha_resolucion' => null,
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => null,
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-018',
                'nombre' => 'JARDINES RURAL',
                'id_comuna' => 4,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 17,
                'nmro_resolucion' => null,
                'fecha_resolucion' => null,
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => null,
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-019',
                'nombre' => 'LOS NARANJOS DE PEÑABLANCA',
                'id_comuna' => 5,
                'supervisor_1' => 'Diego Parra Cartagena',
                'supervisor_2' => 'Margarita Ortiz',
                'nmro_beneficiarios' => 18,
                'nmro_resolucion' => null,
                'fecha_resolucion' => null,
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => null,
                'id_programa' => 5,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-020',
                'nombre' => 'RABUCO DE OCOA III',
                'id_comuna' => 4,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 9,
                'nmro_resolucion' => 9809,
                'fecha_resolucion' => '2024-08-12',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2026-05-12',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-021',
                'nombre' => 'LUIS MORALES MORALES',
                'id_comuna' => 2,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 11380,
                'fecha_resolucion' => '2024-10-04',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2026-07-04',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-022',
                'nombre' => 'ESMERALDA BERNAL',
                'id_comuna' => 4,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 11397,
                'fecha_resolucion' => '2024-10-04',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2026-07-04',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-023',
                'nombre' => 'PC 1 BEZAMA-CONTRERAS-TELLO-RIVAS',
                'id_comuna' => 6,
                'supervisor_1' => 'Diego Parra Cartagena',
                'supervisor_2' => 'Laura Cousiño',
                'nmro_beneficiarios' => 4,
                'nmro_resolucion' => 324,
                'fecha_resolucion' => '2025-02-23',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2026-11-23',
                'id_programa' => 3,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-024',
                'nombre' => 'PC 2 MENDOZA-ZELADA-QUEZADA-MOYA',
                'id_comuna' => 6,
                'supervisor_1' => 'Diego Parra Cartagena',
                'supervisor_2' => 'Claudia Escalante',
                'nmro_beneficiarios' => 4,
                'nmro_resolucion' => 565,
                'fecha_resolucion' => '2025-05-07',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-02-07',
                'id_programa' => 3,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-025',
                'nombre' => 'CLAUDIO ESTAY TAPIA',
                'id_comuna' => 8,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 6806,
                'fecha_resolucion' => '2025-07-01',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-04-01',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-026',
                'nombre' => 'CESAR PINTO MIRANDA',
                'id_comuna' => 7,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 6807,
                'fecha_resolucion' => '2025-07-01',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-04-01',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-027',
                'nombre' => 'JESSICA TAPIA FIERRO',
                'id_comuna' => 8,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 7095,
                'fecha_resolucion' => '2025-07-07',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-04-07',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-028',
                'nombre' => 'MARIA FIGUEROA SALINAS',
                'id_comuna' => 9,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 7505,
                'fecha_resolucion' => '2025-07-18',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-04-18',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-029',
                'nombre' => 'MARCELA GELDES SOLIS',
                'id_comuna' => 4,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 7743,
                'fecha_resolucion' => '2025-07-21',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-04-21',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-030',
                'nombre' => 'ROSA SOLIS OLIVARES',
                'id_comuna' => 4,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 7506,
                'fecha_resolucion' => '2025-07-18',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-04-18',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-031',
                'nombre' => 'NILDA GELDES VERGARA',
                'id_comuna' => 2,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 7744,
                'fecha_resolucion' => '2025-07-21',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-04-21',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-032',
                'nombre' => 'PC 4 VALENZUELA-QUIROZ-FIGUEROA-MARTÍNEZ',
                'id_comuna' => 6,
                'supervisor_1' => 'Nicolas Abarca Palacios',
                'supervisor_2' => 'Benjamín neira',
                'nmro_beneficiarios' => 4,
                'nmro_resolucion' => 477,
                'fecha_resolucion' => '2025-04-08',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-01-08',
                'id_programa' => 3,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-033',
                'nombre' => 'AMPLIACIONES ANDRES BELLO II',
                'id_comuna' => 7,
                'supervisor_1' => 'Mauricio Grandón Sanhueza',
                'supervisor_2' => 'No hay',
                'nmro_beneficiarios' => 10,
                'nmro_resolucion' => 1061,
                'fecha_resolucion' => '2025-08-01',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-05-13',
                'id_programa' => 2,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-034',
                'nombre' => 'PATRIMONIAL PAULA MENA DIAZ',
                'id_comuna' => 11,
                'supervisor_1' => 'Andrea Camus Araya',
                'supervisor_2' => 'No hay',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 1061,
                'fecha_resolucion' => '2025-08-01',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-05-13',
                'id_programa' => 2,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-035',
                'nombre' => 'HUGO TOLOZA',
                'id_comuna' => 7,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 8730,
                'fecha_resolucion' => '2025-08-21',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-05-21',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-036',
                'nombre' => 'CAROLINA OLIVARES TORRES',
                'id_comuna' => 3,
                'supervisor_1' => 'Sebastian Rojo Tapia',
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 11556,
                'fecha_resolucion' => '2025-09-23',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-06-23',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-037',
                'nombre' => 'COMITÉ EL BOCO IV',
                'id_comuna' => 2,
                'supervisor_1' => null,
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 82,
                'nmro_resolucion' => 12633,
                'fecha_resolucion' => '2025-10-10',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-07-10',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-038',
                'nombre' => 'COMITÉ LA VEGA DE OLMUÉ',
                'id_comuna' => 9,
                'supervisor_1' => null,
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 13,
                'nmro_resolucion' => 12618,
                'fecha_resolucion' => '2025-10-09',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-07-09',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-039',
                'nombre' => 'COMITÉ LA VEGA DE OLMUÉ II',
                'id_comuna' => 9,
                'supervisor_1' => null,
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 23,
                'nmro_resolucion' => 12966,
                'fecha_resolucion' => '2025-10-20',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-07-20',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-040',
                'nombre' => 'COMITÉ PUNTA DE TORREJÓN',
                'id_comuna' => 4,
                'supervisor_1' => null,
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 45,
                'nmro_resolucion' => 12965,
                'fecha_resolucion' => '2025-10-20',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-07-20',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-041',
                'nombre' => 'TAMARA ALVAREZ ALVAREZ',
                'id_comuna' => 4,
                'supervisor_1' => null,
                'supervisor_2' => 'Elizabeth Olivares',
                'nmro_beneficiarios' => 1,
                'nmro_resolucion' => 14175,
                'fecha_resolucion' => '2025-11-12',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-08-12',
                'id_programa' => 1,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-042',
                'nombre' => 'PC 3 ALEGRÍA-GELDES-MUÑOZ-VERGARA',
                'id_comuna' => 10,
                'supervisor_1' => 'Nicolas Abarca Palacios',
                'supervisor_2' => 'Claudia Escalante',
                'nmro_beneficiarios' => 4,
                'nmro_resolucion' => 535,
                'fecha_resolucion' => '2025-04-24',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-01-24',
                'id_programa' => 3,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-043',
                'nombre' => 'PC 5 AGUILERA -CONTRERAS-DAZA-FERNÁNDEZ',
                'id_comuna' => 10,
                'supervisor_1' => 'Nicolas Abarca Palacios',
                'supervisor_2' => 'Benjamín neira',
                'nmro_beneficiarios' => 4,
                'nmro_resolucion' => 477,
                'fecha_resolucion' => '2025-04-08',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-01-08',
                'id_programa' => 3,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-044',
                'nombre' => 'PC 8 ALVARADO-MORALES-MUÑOZ-SANTIS',
                'id_comuna' => 10,
                'supervisor_1' => 'Ana Robledo Hinojosa',
                'supervisor_2' => 'Benjamín neira',
                'nmro_beneficiarios' => 4,
                'nmro_resolucion' => 465,
                'fecha_resolucion' => '2025-05-07',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-02-07',
                'id_programa' => 3,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => 'PRY-045',
                'nombre' => 'PC 7 AZOLAS-PEÑA-PONCE-SERRANO',
                'id_comuna' => 10,
                'supervisor_1' => 'Ana Robledo Hinojosa',
                'supervisor_2' => 'Benjamín neira',
                'nmro_beneficiarios' => 4,
                'nmro_resolucion' => 477,
                'fecha_resolucion' => '2025-04-08',
                'fecha_ini_obra' => null,
                'fecha_vencimiento' => '2027-01-08',
                'id_programa' => 3,
                'color' => null,
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
